"""add_unique_constraints

Revision ID: 355c4603dfdb
Revises: b7d2c31e9a3b
Create Date: 2026-09-28 21:04:04.882569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '355c4603dfdb'
down_revision: Union[str, None] = 'b7d2c31e9a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_skill_score_unique', 'skill_scores', ['region', 'season', 'lead_hours', 'parameter', 'source'])
    op.create_unique_constraint('uix_weight_unique', 'weights', ['region', 'season', 'lead_hours', 'parameter', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_weight_unique', 'weights', type_='unique')
    op.drop_constraint('uix_skill_score_unique', 'skill_scores', type_='unique')
    # ### end Alembic commands ###
